name: build docker image

on: 
  workflow_dispatch

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build docker image
        run: |
          docker build -t docker-container-nodejs .

      - name: docker version
        run: |
          docker --version

      - name: docker images
        run: |
          docker images
          
      - name: Scan docker image with trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'docker-container-nodejs:latest'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          
        
      
      
